mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /polls/5/
    url('^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /polls/5/results/
    url('^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # /polls/5/vote/
    url('^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models/choice.py
from django.db import models

import question


class Choice(models.Model):
    question = models.ForeignKey(question.Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/models/question.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from models.question import Question
from models.choice import Choice


class IndexView(generic.ListView):
    model = Question

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lt=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question

    def get_queryset(self):
        return Question.objects.filter(pub_date__lt=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/question_results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',
                      {'question': question, 'error_message': "You didn't select a choice?"})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/question_detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice-{{ choice.id }}" value="{{ choice.id }}"/>
        <label for="choice-{{ choice.id }}">{{ choice.choice_text }}</label><br/>
    {%  endfor %}
    <input type="submit" value="Vote"/>
</form>

polls/templates/polls/question_list.html
{% if question_list  %}
    <ul>
      {% for question in question_list %}
         <li><a href="{% url 'polls:detail' question.id %}" data-question-id="{{ question.id }}">{{ question.question_text }}</a></li>
      {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/question_results.html
<h1>{{ question }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice }} | ({{ choice.votes  }} vote{{ choice.votes|pluralize }})</li>
    {%  endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote Again</a>